services:
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    networks:
      - internal
    volumes:
      - ./../:/application
      - ./sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"

  php-fpm:
    build: sourcefiles/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm

    working_dir: /application
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
    volumes:
      - ./../:/application
      - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - internal
  mariadb:
    image: mariadb:11.7.2
    container_name: ${PROJECT_NAME}-mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    networks:
      - internal

volumes:
  mariadb-data:
    driver: local
networks:
  internal:
    driver: bridge